[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/**/*.ts"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/**/*.tsx"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"